DROP USER SGPF CASCADE;
DROP USER SGPF_FNC CASCADE;

DROP ROLE ROWNER_SGPF_FNC;
DROP ROLE RUSER_SGPF_FNC;

DROP TABLESPACE TBSDATA01_SGPF_FNC INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TBSIDX01_SGPF_FNC INCLUDING CONTENTS AND DATAFILES;


